// Convex access for the eve runtime (hooks + sandbox definition).
// Imported lazily so the agent still boots when convex is not configured.
import { ConvexReactClient } from "convex/react";
// Resolves inside the app root: eve's dev runtime snapshots the app directory
// and cannot follow imports outside it (root convex/_generated is mirrored to
// apps/frontend/convex/_generated by `pnpm convex:codegen`).
import { api } from "../../convex/_generated/api";

let client: ConvexReactClient | null = null;

export function convex() {
  const url = process.env.NEXT_PUBLIC_CONVEX_URL;
  if (!url) throw new Error("NEXT_PUBLIC_CONVEX_URL is not set");
  client ??= new ConvexReactClient(url);
  return client;
}

export { api };
